version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: maliknet-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: maliknet
    ports:
      - "5432:5432"
    volumes:
      - my_db_volume:/var/lib/postgresql/data
    networks:
      - maliknet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d maliknet"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maliknet-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/maliknet
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    networks:
      - maliknet-network

volumes:
  my_db_volume:

networks:
  maliknet-network:
    driver: bridge
